"""
Public API for hazard-conditioned functional message passing.

Target path:
    urban_resilience_models/
        v2_hazard_conditioned_functional_ugnn/
            functional_message_passing/
                __init__.py

This package exposes the complete bounded V2.0 functional-message-passing
subsystem:

- metadata-preserving FMP inputs, stage outputs, and lineage contracts;
- validated generic grouped tensor operations;
- shared and exact-relation source-state transforms;
- structural edge normalization;
- exact target-node message aggregation;
- hazard-conditioned exact-relation gating;
- exact target-node/relation edge attention;
- explicit edge-message coefficient resolution and composition;
- complete one-layer orchestration;
- multi-layer stack orchestration, sharing, retention, traces, and diagnostics.

Dependency direction
--------------------
The public modules are imported in numerical-stage order:

    schemas
        -> segment operations
        -> relation transforms
        -> structural edge normalization
        -> target-node aggregation
        -> relation gating
        -> edge attention
        -> message construction
        -> one-layer orchestration
        -> multi-layer stack orchestration

Importing this package does not:

- construct model components;
- compile or mutate relation registries;
- move tensors between devices;
- execute message passing;
- enable diagnostics;
- retain audit traces;
- construct ablation experiments.

``ablations.py`` is currently an empty placeholder and is intentionally not
part of the public API.

Collision policy
----------------
A few subpackages publish historically overlapping names. This root namespace
never relies on silent last-import-wins behavior:

- the authoritative stack output is
  ``stack.FunctionalMessagePassingStackOutput``;
- the historical top-level stack schema remains available as
  ``LegacyFunctionalMessagePassingStackOutput``;
- historical FMP-wide gate, attention, and message schemas use explicit
  ``FunctionalMessagePassing...`` aliases;
- generic diagnostic helpers from the message-builder and layer subsystems
  receive subsystem-qualified root aliases.

All original names remain available from their owning subpackages.

Boundary
-------------------
Transforms, gates, attention values, edge messages, aggregates, state
transitions, retained traces, regularization terms, and diagnostic summaries
are descriptive model quantities. They do not by themselves establish causal
influence, explanation faithfulness, calibrated uncertainty, counterfactual
validity, or mechanistic identifiability.
"""

from __future__ import annotations


# =============================================================================
# Package identity
# =============================================================================

FUNCTIONAL_MESSAGE_PASSING_PACKAGE_API_VERSION = "0.1"


# =============================================================================
# Public module namespaces
# =============================================================================

from . import (
    schemas,
    segment_ops,
    relation_transforms,
    edge_normalization,
    aggregators,
    relation_family_gate,
    edge_attention,
    message_builders,
    layer,
    stack,
)


# =============================================================================
# Metadata-preserving schemas
# =============================================================================

from .schemas import (
    AGGREGATION_OUTPUT_SCHEMA_VERSION,
    EDGE_ATTENTION_OUTPUT_SCHEMA_VERSION,
    EDGE_MESSAGE_OUTPUT_SCHEMA_VERSION,
    EDGE_NORMALIZATION_OUTPUT_SCHEMA_VERSION,
    FMP_INTERMEDIATES_SCHEMA_VERSION,
    FMP_LAYER_OUTPUT_SCHEMA_VERSION,
    FMP_NODE_STATE_SOURCE_LAYER_OUTPUT,
    FMP_STACK_OUTPUT_SCHEMA_VERSION,
    FUNCTIONAL_MESSAGE_PASSING_INPUT_SCHEMA_VERSION,
    FUNCTIONAL_MESSAGE_PASSING_NODE_STATE_SCHEMA_VERSION,
    RELATION_FAMILY_ALIGNMENT_SCHEMA_VERSION,
    RELATION_GATE_OUTPUT_SCHEMA_VERSION,
    RELATION_TRANSFORM_OUTPUT_SCHEMA_VERSION,
    AggregationOutput,
    EdgeAttentionOutput as FunctionalMessagePassingEdgeAttentionOutput,
    EdgeMessageOutput as FunctionalMessagePassingEdgeMessageOutput,
    FunctionalMessagePassingInputs,
    FunctionalMessagePassingIntermediates,
    FunctionalMessagePassingLayerOutput,
    FunctionalMessagePassingNodeState,
    FunctionalMessagePassingStackOutput as LegacyFunctionalMessagePassingStackOutput,
    RelationFamilyAlignment,
    RelationGateOutput as FunctionalMessagePassingRelationGateOutput,
    RelationTransformOutput,
    StructuralEdgeNormalizationOutput,
)


# =============================================================================
# Generic grouped tensor operations
# =============================================================================

from .segment_ops import (
    SEGMENT_OPS_SCHEMA_VERSION,
    SegmentMaxResult,
    assert_grouped_softmax_normalized,
    grouped_softmax,
    grouped_softmax_sums,
    segment_counts,
    segment_max,
    segment_mean,
    segment_presence,
    segment_sum,
    validate_segment_ids,
)


# =============================================================================
# Relation transforms
# =============================================================================

from .relation_transforms import (
    PER_RELATION_TRANSFORM_SCHEMA_VERSION,
    RELATION_TRANSFORMS_DISPATCHER_SCHEMA_VERSION,
    SHARED_RELATION_TRANSFORM_SCHEMA_VERSION,
    PerRelationTransform,
    RelationTransforms,
    SharedRelationTransform,
)


# =============================================================================
# Structural edge normalization
# =============================================================================

from .edge_normalization import (
    EDGE_NORMALIZATION_SCHEMA_VERSION,
    EdgeNormalization,
)


# =============================================================================
# Target-node aggregation
# =============================================================================

from .aggregators import (
    AGGREGATOR_SCHEMA_VERSION,
    Aggregator,
    MessageAggregator,
)


# =============================================================================
# Hazard-conditioned relation gating
# =============================================================================

from .relation_family_gate import (
    GATE_ACTIVATION_OUTPUT_SCHEMA_VERSION,
    GATE_NETWORK_OUTPUT_SCHEMA_VERSION,
    RELATION_FAMILY_GATE_SCHEMA_VERSION,
    RELATION_GATE_ACTIVATIONS_SCHEMA_VERSION,
    RELATION_GATE_AXIS_SCHEMA_VERSION,
    RELATION_GATE_NETWORK_SCHEMA_VERSION,
    RELATION_PRIOR_CONTRIBUTION_SCHEMA_VERSION,
    RELATION_PRIOR_INTEGRATION_SCHEMA_VERSION,
    GateActivationOutput,
    GateNetworkOutput,
    RelationGateAxis,
    RelationGateOutput,
    RelationPriorContribution,
    GateNetwork,
    RelationGateNetwork,
    RelationPriorBuilder,
    RelationPriorContributionBuilder,
    RelationPriorIntegration,
    GateActivation,
    RelationGateActivation,
    apply_relation_gate_activation,
    sigmoid_gate_activation,
    RelationFamilyGate,
    RelationGate,
)


# =============================================================================
# Exact-relation edge attention
# =============================================================================

from .edge_attention import (
    ATTENTION_HEAD_REDUCTION_OUTPUT_SCHEMA_VERSION,
    ATTENTION_NORMALIZATION_OUTPUT_SCHEMA_VERSION,
    EDGE_ATTENTION_SCORE_OUTPUT_SCHEMA_VERSION,
    EDGE_ATTENTION_SCORE_FUNCTIONS_SCHEMA_VERSION,
    ATTENTION_NORMALIZATION_SCHEMA_VERSION,
    ATTENTION_MULTIHEAD_SCHEMA_VERSION,
    EDGE_ATTENTION_ORCHESTRATOR_SCHEMA_VERSION,
    EDGE_ATTENTION_SCHEMA_MODES,
    EDGE_ATTENTION_SCORE_MODES,
    LEARNED_EDGE_ATTENTION_MODES,
    IMPLEMENTED_ATTENTION_NORMALIZATION_MODES,
    IMPLEMENTED_ATTENTION_HEAD_REDUCTIONS,
    EDGE_ATTENTION_SCORE_FUNCTION_UNIFORM,
    EDGE_ATTENTION_SCORE_FUNCTION_ADDITIVE,
    EDGE_ATTENTION_INPUT_SOURCE_NODE_STATE,
    EDGE_ATTENTION_INPUT_TARGET_NODE_STATE,
    EDGE_ATTENTION_INPUT_TARGET_HAZARD_QUERY,
    EDGE_ATTENTION_INPUT_EXACT_RELATION_EMBEDDING,
    ATTENTION_GROUP_KEY_TARGET_NODE_EXACT_RELATION,
    ATTENTION_GROUP_ID_FORMULA,
    ATTENTION_HEAD_MEAN_FORMULA,
    ATTENTION_HEAD_REDUCTION_INTERPRETATION,
    EDGE_ATTENTION_GROUP_SEMANTICS,
    EDGE_ATTENTION_OPERATION_ORDER,
    EDGE_ATTENTION_SCIENTIFIC_INTERPRETATION,
    DEFAULT_EDGE_ATTENTION_HIDDEN_DIM,
    EdgeAttentionScoreOutput,
    AttentionNormalizationOutput,
    AttentionHeadReductionOutput,
    EdgeAttentionOutput,
    EdgeAttentionStages,
    EdgeAttentionScoreFunction,
    UniformEdgeAttentionScoreFunction,
    UniformAttentionScoreFunction,
    AdditiveEdgeAttentionScoreFunction,
    AdditiveAttentionScoreFunction,
    build_edge_attention_score_function,
    build_attention_score_function,
    AttentionNormalizer,
    TargetNodeRelationAttentionNormalization,
    AttentionNormalization,
    EdgeAttentionNormalizer,
    build_target_node_relation_group_ids,
    build_target_node_relation_group_counts,
    normalize_attention_logits,
    normalize_edge_attention_scores,
    apply_attention_normalization,
    build_attention_normalizer,
    build_edge_attention_normalizer,
    attention_group_sums,
    assert_attention_normalized,
    maximum_attention_normalization_error,
    AttentionHeadReducer,
    MeanAttentionHeadReduction,
    AttentionHeadReduction,
    MultiheadAttentionReduction,
    EdgeAttentionHeadReducer,
    mean_reduce_attention_heads,
    reduce_attention_heads,
    reduce_normalized_attention_heads,
    apply_attention_head_reduction,
    build_attention_head_reducer,
    build_edge_attention_head_reducer,
    assert_reduced_attention_normalized,
    maximum_reduced_attention_normalization_error,
    attention_head_mean,
    attention_head_variance,
    attention_head_standard_deviation,
    attention_head_range,
    attention_head_mean_absolute_deviation,
    maximum_attention_head_range,
    mean_attention_head_standard_deviation,
    head_disagreement_summary,
    EdgeAttention,
    EdgeAttentionModule,
    FunctionalEdgeAttention,
    HazardConditionedEdgeAttention,
    assemble_edge_attention_output,
    build_edge_attention,
    build_edge_attention_module,
    run_edge_attention,
)


# =============================================================================
# Edge-message construction
# =============================================================================

from .message_builders import (
    MESSAGE_BUILDERS_PACKAGE_API_VERSION,
    RESOLVED_MESSAGE_COEFFICIENTS_SCHEMA_VERSION,
    MESSAGE_COMPOSITION_OUTPUT_SCHEMA_VERSION,
    MESSAGE_SEMANTIC_EDGE_POLICY_IGNORE,
    MESSAGE_SEMANTIC_EDGE_POLICY_USE_SOURCE_GRAPH,
    CANONICAL_MESSAGE_SEMANTIC_EDGE_POLICIES,
    IMPLEMENTED_MESSAGE_SEMANTIC_EDGE_POLICIES,
    MESSAGE_FACTOR_STRUCTURAL_NORMALIZATION,
    MESSAGE_FACTOR_RELATION_GATE,
    MESSAGE_FACTOR_EDGE_ATTENTION,
    MESSAGE_FACTOR_SEMANTIC_EDGE_WEIGHT,
    MESSAGE_FACTOR_ORDER,
    MESSAGE_DISABLED_FACTOR_POLICY,
    MESSAGE_TRANSFORM_INPUT_LAYOUT,
    MESSAGE_COMBINED_COEFFICIENT_FORMULA,
    MESSAGE_COMPOSITION_FORMULA,
    ResolvedMessageCoefficients,
    MessageCoefficients,
    MessageCompositionOutput,
    EdgeMessageCompositionOutput,
    MessageBuilderStages,
    EdgeMessageOutput,
    validate_message_builder_stage_chain,
    validate_public_edge_message_output,
    RELATION_STATE_GATHER_SCHEMA_VERSION,
    RELATION_STATE_GATHER_OPERATION,
    RELATION_STATE_GATHER_INPUT_LAYOUT,
    RELATION_STATE_GATHER_OUTPUT_LAYOUT,
    RELATION_STATE_GATHER_OWNER,
    RELATION_STATE_GATHER_INDEXING_OWNED_HERE,
    RELATION_STATE_GATHER_ZERO_COPY_REQUIRED,
    RELATION_STATE_GATHER_PARAMETER_FREE,
    RELATION_STATE_GATHER_OPERATION_ORDER,
    relation_state_gather_architecture_dict,
    relation_state_gather_architecture_fingerprint,
    validate_edge_aligned_relation_state,
    assert_zero_copy_relation_state,
    resolve_edge_aligned_relation_state,
    resolve_relation_state,
    gather_relation_state,
    relation_state_gather_diagnostic_summary,
    validate_relation_state_gather_contract,
    RelationStateGather,
    RelationStateResolver,
    EdgeAlignedRelationStateResolver,
    build_relation_state_gather,
    build_relation_state_resolver,
    MESSAGE_COEFFICIENT_RESOLUTION_SCHEMA_VERSION,
    MESSAGE_COEFFICIENT_RESOLUTION_OPERATION_ORDER,
    MESSAGE_COEFFICIENT_RESOLUTION_INTERPRETATION,
    MESSAGE_COEFFICIENT_RESOLUTION_PARAMETER_FREE,
    MESSAGE_COEFFICIENT_RESOLUTION_BUFFER_FREE,
    OptionalFactorResolution,
    SemanticFactorResolution,
    resolve_structural_normalization_factor,
    resolve_relation_gate_factor,
    resolve_edge_attention_factor,
    resolve_semantic_edge_factor,
    combine_message_coefficients,
    coefficient_resolution_architecture_dict,
    coefficient_resolution_architecture_fingerprint,
    resolve_message_coefficients,
    resolve_edge_message_coefficients,
    validate_resolved_message_coefficients,
    message_coefficient_diagnostic_summary,
    MessageCoefficientResolver,
    CoefficientResolver,
    EdgeMessageCoefficientResolver,
    build_message_coefficient_resolver,
    build_coefficient_resolver,
    MESSAGE_COMPOSER_SCHEMA_VERSION,
    MESSAGE_COMPOSER_OPERATION,
    MESSAGE_COMPOSER_OPERATION_ORDER,
    MESSAGE_COMPOSER_INPUT_STATE_LAYOUT,
    MESSAGE_COMPOSER_INPUT_COEFFICIENT_LAYOUT,
    MESSAGE_COMPOSER_OUTPUT_LAYOUT,
    MESSAGE_COMPOSER_BROADCAST_AXIS,
    MESSAGE_COMPOSER_PARAMETER_FREE,
    MESSAGE_COMPOSER_BUFFER_FREE,
    MESSAGE_COMPOSER_AGGREGATION_OWNED_HERE,
    message_composer_architecture_dict,
    message_composer_architecture_fingerprint,
    compose_edge_message_tensor,
    compose_message_vectors,
    compose_message_output,
    compose_edge_messages,
    validate_message_composition_output,
    message_composition_diagnostic_summary,
    EdgeMessageComposer,
    MessageComposer,
    FunctionalMessageComposer,
    build_edge_message_composer,
    build_message_composer,
    MESSAGE_BUILDER_DIAGNOSTICS_SCHEMA_VERSION,
    MESSAGE_BUILDER_DIAGNOSTICS_INTERPRETATION,
    MESSAGE_BUILDER_DIAGNOSTICS_OPERATION_ORDER,
    MESSAGE_BUILDER_DIAGNOSTICS_PARAMETER_FREE,
    MESSAGE_BUILDER_DIAGNOSTICS_BUFFER_FREE,
    MESSAGE_BUILDER_DIAGNOSTIC_SECTION_STAGE_SUMMARIES,
    MESSAGE_BUILDER_DIAGNOSTIC_SECTION_GLOBAL,
    MESSAGE_BUILDER_DIAGNOSTIC_SECTION_BY_RELATION,
    MESSAGE_BUILDER_DIAGNOSTIC_SECTION_BY_GRAPH,
    MESSAGE_BUILDER_DIAGNOSTIC_SECTION_LINEAGE,
    MESSAGE_BUILDER_DIAGNOSTIC_SECTION_ALERTS,
    MESSAGE_BUILDER_DIAGNOSTIC_REQUIRED_SECTIONS,
    MessageBuilderDiagnosticThresholds,
    DEFAULT_MESSAGE_BUILDER_DIAGNOSTIC_THRESHOLDS,
    scalar_tensor_statistics as message_builder_scalar_tensor_statistics,
    edge_vector_norm_statistics,
    factor_statistics,
    exact_relation_diagnostics,
    graph_batch_diagnostics as message_builder_graph_batch_diagnostics,
    message_builder_lineage_summary,
    derive_message_builder_alerts,
    message_builder_diagnostics_architecture_dict,
    message_builder_diagnostics_architecture_fingerprint,
    build_message_builder_diagnostic_report,
    message_builder_diagnostic_report,
    build_public_edge_message_diagnostic_report,
    public_edge_message_diagnostic_report,
    diagnostic_report_fingerprint,
    validate_message_builder_diagnostic_report,
    MessageBuilderDiagnostics,
    MessageDiagnostics,
    EdgeMessageDiagnostics,
    build_message_builder_diagnostics,
    build_edge_message_diagnostics,
    MESSAGE_BUILDERS_ORCHESTRATOR_SCHEMA_VERSION,
    MESSAGE_BUILDERS_OPERATION_ORDER,
    MESSAGE_BUILDERS_SCIENTIFIC_INTERPRETATION,
    MESSAGE_BUILDERS_DISABLED_GATE_REPRESENTATION,
    MESSAGE_BUILDERS_DISABLED_ATTENTION_REPRESENTATION,
    MESSAGE_BUILDERS_PARAMETER_FREE,
    MESSAGE_BUILDERS_BUFFER_FREE,
    MESSAGE_BUILDERS_AGGREGATION_OWNED_HERE,
    MESSAGE_BUILDERS_OUTPUT_SCHEMA,
    MessageBuilderRun,
    MessageBuilderRunWithDiagnostics,
    assemble_edge_message_output,
    validate_complete_message_builder_run,
    EdgeMessageBuilder,
    MessageBuilder,
    FunctionalMessageBuilder,
    FunctionalEdgeMessageBuilder,
    build_edge_message_builder,
    build_message_builder,
    build_message_builders,
    run_edge_message_builder,
    run_message_builder,
    run_edge_message_builder_stages,
    run_message_builder_stages,
)


# =============================================================================
# Complete one-layer orchestration
# =============================================================================

from .layer import (
    LAYER_PACKAGE_API_VERSION,
    LAYER_INPUTS_SCHEMA_VERSION,
    LAYER_TRACE_POLICY_SCHEMA_VERSION,
    LAYER_RESIDUAL_UPDATE_SCHEMA_VERSION,
    LAYER_NORMALIZATION_OUTPUT_SCHEMA_VERSION,
    LAYER_INTERMEDIATE_TRACE_SCHEMA_VERSION,
    LAYER_COMPUTATION_OUTPUT_SCHEMA_VERSION,
    LAYER_TRACE_NONE,
    LAYER_TRACE_NODE,
    LAYER_TRACE_FULL,
    CANONICAL_LAYER_TRACE_MODES,
    V2_0_IMPLEMENTED_LAYER_TRACE_MODES,
    LayerTracePolicy,
    LAYER_RESIDUAL_DISABLED,
    LAYER_RESIDUAL_ADDITIVE,
    CANONICAL_LAYER_RESIDUAL_MODES,
    V2_0_IMPLEMENTED_LAYER_RESIDUAL_MODES,
    LAYER_NORMALIZATION_NONE,
    LAYER_NORMALIZATION_LAYER_NORM,
    CANONICAL_LAYER_NORMALIZATION_MODES,
    V2_0_IMPLEMENTED_LAYER_NORMALIZATION_MODES,
    LAYER_NORMALIZATION_PRE_RESIDUAL,
    LAYER_NORMALIZATION_POST_RESIDUAL,
    CANONICAL_LAYER_NORMALIZATION_POSITIONS,
    V2_0_IMPLEMENTED_LAYER_NORMALIZATION_POSITIONS,
    LAYER_UPDATE_BRANCH_FORMULA,
    LAYER_ADDITIVE_RESIDUAL_FORMULA,
    LAYER_DISABLED_RESIDUAL_FORMULA,
    LAYER_POST_NORMALIZATION_FORMULA,
    LAYER_INPUT_LAYOUT,
    LAYER_AGGREGATE_LAYOUT,
    LAYER_OUTPUT_LAYOUT,
    LAYER_SCIENTIFIC_INTERPRETATION,
    FunctionalMessagePassingLayerInputs,
    LayerInputs,
    LayerResidualUpdateOutput,
    ResidualUpdateOutput,
    LayerNormalizationOutput,
    NormalizationOutput,
    FunctionalMessagePassingLayerTrace,
    LayerTrace,
    LayerComputationOutput,
    FunctionalMessagePassingLayerComputation,
    FunctionalMessagePassingLayerStages,
    LayerStages,
    validate_layer_stage_chain,
    build_public_layer_intermediates,
    validate_public_layer_output,
    layer_schema_architecture_dict,
    layer_schema_architecture_fingerprint,
    LAYER_RESIDUAL_UPDATER_SCHEMA_VERSION,
    LAYER_RESIDUAL_UPDATER_OPERATION,
    LAYER_RESIDUAL_UPDATER_OPERATION_ORDER,
    LAYER_RESIDUAL_UPDATER_PARAMETER_FREE,
    LAYER_RESIDUAL_UPDATER_BUFFER_FREE,
    LAYER_RESIDUAL_UPDATER_PROJECTION_OWNED_HERE,
    LAYER_RESIDUAL_UPDATER_AGGREGATION_OWNED_HERE,
    LAYER_RESIDUAL_UPDATER_NORMALIZATION_OWNED_HERE,
    LAYER_DROPOUT_SEMANTICS,
    LAYER_DISABLED_DROPOUT_IDENTITY_POLICY,
    LAYER_DISABLED_RESIDUAL_IDENTITY_POLICY,
    residual_mode_from_enabled,
    residual_enabled_from_mode,
    layer_residual_updater_architecture_dict,
    layer_residual_updater_architecture_fingerprint,
    apply_layer_update_dropout,
    apply_update_dropout,
    apply_layer_residual,
    apply_residual,
    build_layer_residual_update_output,
    apply_layer_residual_update,
    resolve_layer_residual_update,
    validate_layer_residual_update_output,
    layer_residual_update_diagnostic_summary,
    LayerResidualUpdater,
    ResidualUpdater,
    FunctionalResidualUpdater,
    MessagePassingResidualUpdater,
    build_layer_residual_updater,
    build_residual_updater,
    build_layer_residual_updater_from_flags,
    build_residual_updater_from_flags,
    LAYER_NORMALIZER_SCHEMA_VERSION,
    LAYER_NORMALIZER_OPERATION,
    LAYER_NORMALIZER_OPERATION_ORDER,
    LAYER_NORMALIZER_NORMALIZED_AXIS,
    LAYER_NORMALIZER_STATISTIC_SCOPE,
    LAYER_NORMALIZER_VARIANCE_ESTIMATOR,
    LAYER_NORMALIZER_AGGREGATION_OWNED_HERE,
    LAYER_NORMALIZER_DROPOUT_OWNED_HERE,
    LAYER_NORMALIZER_RESIDUAL_OWNED_HERE,
    LAYER_NORMALIZER_MULTI_LAYER_ITERATION_OWNED_HERE,
    LAYER_DISABLED_NORMALIZATION_IDENTITY_POLICY,
    LAYER_NORMALIZER_DEFAULT_EPSILON,
    LAYER_NORMALIZER_DEFAULT_ELEMENTWISE_AFFINE,
    LAYER_NORMALIZER_DEFAULT_BIAS_ENABLED,
    normalization_mode_from_enabled,
    normalization_enabled_from_mode,
    layer_normalizer_architecture_dict,
    layer_normalizer_architecture_fingerprint,
    apply_layer_normalization,
    apply_normalization,
    build_layer_normalization_output,
    normalize_layer_state,
    resolve_layer_normalization,
    validate_layer_normalization_output,
    layer_normalization_diagnostic_summary,
    LayerNormalizer,
    FunctionalLayerNormalizer,
    MessagePassingLayerNormalizer,
    PostResidualLayerNormalizer,
    build_layer_normalizer,
    build_normalizer,
    build_layer_normalizer_from_flag,
    build_normalizer_from_flag,
    LAYER_DIAGNOSTICS_SCHEMA_VERSION,
    LAYER_DIAGNOSTICS_INTERPRETATION,
    LAYER_DIAGNOSTICS_OPERATION_ORDER,
    LAYER_DIAGNOSTICS_PARAMETER_FREE,
    LAYER_DIAGNOSTICS_BUFFER_FREE,
    LAYER_DIAGNOSTICS_IMPLICIT_FORWARD_EXECUTION,
    LAYER_DIAGNOSTIC_SECTION_STAGE_SUMMARIES,
    LAYER_DIAGNOSTIC_SECTION_GLOBAL,
    LAYER_DIAGNOSTIC_SECTION_BY_GRAPH,
    LAYER_DIAGNOSTIC_SECTION_TRACE,
    LAYER_DIAGNOSTIC_SECTION_REGULARIZATION,
    LAYER_DIAGNOSTIC_SECTION_LINEAGE,
    LAYER_DIAGNOSTIC_SECTION_ALERTS,
    LAYER_DIAGNOSTIC_REQUIRED_SECTIONS,
    LayerDiagnosticThresholds,
    DEFAULT_LAYER_DIAGNOSTIC_THRESHOLDS,
    scalar_tensor_statistics as layer_scalar_tensor_statistics,
    matrix_statistics,
    state_transition_statistics,
    incoming_edge_count_statistics,
    aggregation_diagnostic_summary,
    graph_batch_diagnostics as layer_graph_batch_diagnostics,
    layer_trace_diagnostic_summary,
    layer_lineage_summary,
    regularization_diagnostic_summary,
    derive_layer_alerts,
    layer_diagnostics_architecture_dict,
    layer_diagnostics_architecture_fingerprint,
    build_layer_diagnostic_report,
    layer_diagnostic_report,
    build_public_layer_diagnostic_report,
    public_layer_diagnostic_report,
    layer_diagnostic_report_fingerprint,
    validate_layer_diagnostic_report,
    LayerDiagnostics,
    FunctionalLayerDiagnostics,
    MessagePassingLayerDiagnostics,
    build_layer_diagnostics,
    build_functional_layer_diagnostics,
    build_message_passing_layer_diagnostics,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_SCHEMA_VERSION,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_OPERATION_ORDER,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_SCIENTIFIC_INTERPRETATION,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_OUTPUT_SCHEMA,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_AGGREGATION_ORCHESTRATED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_AGGREGATION_MATH_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_STACKING_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_PREDICTION_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_DISABLED_GATE_REPRESENTATION,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_DISABLED_ATTENTION_REPRESENTATION,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_UNIFORM_ATTENTION_REPRESENTATION,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_TRACE_AFFECTS_NUMERICS,
    FUNCTIONAL_MESSAGE_PASSING_LAYER_DIAGNOSTICS_AFFECT_NUMERICS,
    FunctionalMessagePassingLayerEdgeStages,
    LayerEdgeStages,
    FunctionalMessagePassingLayerNodeStages,
    LayerNodeStages,
    FunctionalMessagePassingLayerRun,
    LayerRun,
    FunctionalMessagePassingLayerRunWithDiagnostics,
    LayerRunWithDiagnostics,
    assemble_functional_message_passing_layer_output,
    validate_functional_message_passing_layer_run,
    FunctionalMessagePassingLayer,
    HazardConditionedFunctionalMessagePassingLayer,
    FunctionalLayer,
    MessagePassingLayer,
    build_functional_message_passing_layer,
    build_layer,
    build_functional_message_passing_layer_from_config,
    build_layer_from_config,
    run_functional_message_passing_layer,
    run_layer,
    run_functional_message_passing_layer_complete,
    run_layer_complete,
)


# =============================================================================
# Complete multi-layer stack orchestration
# =============================================================================

from .stack import (
    FUNCTIONAL_MESSAGE_PASSING_STACK_SCHEMA_VERSION,
    STACK_INPUTS_SCHEMA_VERSION,
    STACK_DEPTH_RECORD_SCHEMA_VERSION,
    STACK_TRACE_SCHEMA_VERSION,
    STACK_COMPUTATION_OUTPUT_SCHEMA_VERSION,
    STACK_PUBLIC_OUTPUT_SCHEMA_VERSION,
    STACK_RUN_SCHEMA_VERSION,
    STACK_RUN_WITH_DIAGNOSTICS_SCHEMA_VERSION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_OPERATION_ORDER,
    FUNCTIONAL_MESSAGE_PASSING_STACK_SCIENTIFIC_INTERPRETATION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_OUTPUT_SCHEMA,
    FUNCTIONAL_MESSAGE_PASSING_STACK_REIMPLEMENTS_LAYER_MATH,
    FUNCTIONAL_MESSAGE_PASSING_STACK_RETENTION_AFFECTS_NUMERICS,
    FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_TRACE_AFFECTS_NUMERICS,
    FUNCTIONAL_MESSAGE_PASSING_STACK_DIAGNOSTICS_AFFECT_NUMERICS,
    FUNCTIONAL_MESSAGE_PASSING_STACK_HIDDEN_WIDTH_CHANGES_SUPPORTED,
    FUNCTIONAL_MESSAGE_PASSING_STACK_ZERO_LAYER_SUPPORTED,
    FUNCTIONAL_MESSAGE_PASSING_STACK_PARTIAL_SHARING_SUPPORTED,
    expected_retained_layer_indices,
    FunctionalMessagePassingStackInputs,
    StackInputs,
    FunctionalMessagePassingStackDepthRecord,
    StackDepthRecord,
    FunctionalMessagePassingStackTrace,
    StackTrace,
    FunctionalMessagePassingStackComputationOutput,
    StackComputationOutput,
    FunctionalMessagePassingStackOutput,
    StackOutput,
    FunctionalMessagePassingStackRun,
    StackRun,
    FunctionalMessagePassingStackRunWithDiagnostics,
    StackRunWithDiagnostics,
    assemble_functional_message_passing_stack_output,
    assemble_stack_output,
    validate_public_stack_output,
    validate_functional_message_passing_stack_run,
    validate_stack_run,
    STACK_SHARING_POLICY_SCHEMA_VERSION,
    STACK_LAYER_SHARING_PLAN_SCHEMA_VERSION,
    STACK_SHARING_POLICY_AFFECTS_NUMERICAL_ARCHITECTURE,
    STACK_SHARING_POLICY_AFFECTS_PARAMETER_OWNERSHIP,
    STACK_SHARING_POLICY_AFFECTS_TRACE_DETAIL,
    STACK_SHARING_POLICY_AFFECTS_OUTPUT_RETENTION,
    STACK_SHARING_POLICY_AFFECTS_DIAGNOSTICS,
    STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_MODULES,
    STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_PARAMETERS,
    STACK_SHARING_FULLY_SHARED_REQUIRES_EXACT_MODULE_REUSE,
    STACK_SHARING_PARTIAL_SUPPORTED,
    STACK_SHARING_SCIENTIFIC_INTERPRETATION,
    INDEPENDENT_LAYER_STATE_DICT_PREFIX,
    FULLY_SHARED_LAYER_STATE_DICT_PREFIX,
    normalize_stack_sharing_policy,
    normalize_sharing_policy,
    assert_stack_sharing_policy_implemented,
    is_independent_stack_sharing_policy,
    is_fully_shared_stack_sharing_policy,
    StackSharingPolicy,
    SharingPolicy,
    resolve_stack_sharing_policy,
    resolve_sharing_policy,
    StackLayerSharingPlan,
    LayerSharingPlan,
    build_independent_stack_layer_sharing_plan,
    build_fully_shared_stack_layer_sharing_plan,
    build_stack_layer_sharing_plan,
    build_layer_sharing_plan,
    build_stack_layer_sharing_plan_from_factory,
    build_layer_sharing_plan_from_factory,
    validate_stack_layer_sharing_plan,
    validate_layer_sharing_plan,
    layer_for_stack_depth,
    STACK_RETENTION_POLICY_SCHEMA_VERSION,
    STACK_TRACE_POLICY_SCHEMA_VERSION,
    STACK_TRACE_DECISION_SCHEMA_VERSION,
    STACK_RETENTION_AFFECTS_NUMERICAL_RESULTS,
    STACK_LAYER_TRACE_AFFECTS_NUMERICAL_RESULTS,
    STACK_AUDIT_MODE_AFFECTS_NUMERICAL_RESULTS,
    STACK_RETENTION_NONE_RETAINS_FINAL_LAYER,
    STACK_RETENTION_FINAL_LAYER_RETAINS_FINAL_LAYER,
    STACK_RETENTION_ALL_LAYERS_RETAINS_FINAL_LAYER,
    STACK_RETENTION_POLICY_IS_OUTPUT_CONTRACT,
    STACK_LAYER_TRACE_POLICY_IS_OUTPUT_CONTRACT,
    STACK_TRACE_POLICY_IS_NUMERICAL_ARCHITECTURE,
    STACK_TRACE_POLICY_SCIENTIFIC_INTERPRETATION,
    normalize_stack_retention_policy,
    normalize_retention_policy,
    assert_stack_retention_policy_implemented,
    resolve_stack_retention_policy,
    resolve_retention_policy,
    is_no_stack_retention,
    is_final_layer_stack_retention,
    is_all_layers_stack_retention,
    StackRetentionPolicy,
    RetentionPolicy,
    StackTraceDecision,
    TraceDecision,
    StackTracePolicy,
    TracePolicy,
    resolve_stack_trace_policy,
    resolve_trace_policy,
    build_stack_trace_policy,
    build_trace_policy,
    build_stack_trace_decisions,
    build_trace_decisions,
    validate_stack_trace_decisions,
    validate_trace_decisions,
    validate_retained_layer_indices,
    assert_stack_trace_policy_matches,
    stack_trace_policies_are_numerically_equivalent,
    STACK_DIAGNOSTIC_THRESHOLDS_SCHEMA_VERSION,
    STACK_DEPTH_DIAGNOSTIC_SCHEMA_VERSION,
    STACK_DIAGNOSTIC_REPORT_SCHEMA_VERSION,
    STACK_DIAGNOSTICS_SCHEMA_VERSION,
    STACK_DIAGNOSTICS_AFFECT_NUMERICAL_RESULTS,
    STACK_DIAGNOSTICS_RETAIN_AUTOGRAD_REFERENCES,
    STACK_DIAGNOSTICS_RETURN_TENSORS,
    STACK_DIAGNOSTICS_ESTABLISH_CAUSALITY,
    STACK_DIAGNOSTICS_ESTABLISH_FAITHFULNESS,
    STACK_DIAGNOSTICS_ESTABLISH_CALIBRATION,
    STACK_DIAGNOSTICS_ESTABLISH_IDENTIFIABILITY,
    STACK_DIAGNOSTIC_DEPTH_SOURCE_AUDIT_TRACE,
    STACK_DIAGNOSTIC_DEPTH_SOURCE_RETAINED_OUTPUT,
    STACK_DIAGNOSTIC_DEPTH_SOURCE_UNAVAILABLE,
    CANONICAL_STACK_DIAGNOSTIC_DEPTH_SOURCES,
    STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_COLLAPSE,
    STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_EXPLOSION,
    STACK_DIAGNOSTIC_ALERT_TOTAL_UPDATE_LARGE,
    STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_COLLAPSE,
    STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_EXPLOSION,
    STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_LARGE,
    STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_TINY,
    STACK_DIAGNOSTIC_ALERT_DEPTH_DIRECTION_REVERSAL,
    STACK_DIAGNOSTIC_ALERT_INCOMPLETE_DEPTH_COVERAGE,
    STACK_DIAGNOSTIC_ALERT_SHARED_PARAMETER_DRIFT,
    STACK_DIAGNOSTIC_ALERT_SHARED_ARCHITECTURE_DRIFT,
    STACK_DIAGNOSTIC_SCIENTIFIC_CLAIMS,
    StackDiagnosticThresholds,
    DiagnosticThresholds,
    StackDepthDiagnostic,
    DepthDiagnostic,
    FunctionalMessagePassingStackDiagnosticReport,
    StackDiagnosticReport,
    build_functional_message_passing_stack_diagnostic_report,
    build_stack_diagnostic_report,
    build_diagnostic_report,
    validate_functional_message_passing_stack_diagnostic_report,
    validate_stack_diagnostic_report,
    validate_diagnostic_report,
    FunctionalMessagePassingStackDiagnostics,
    StackDiagnostics,
    FUNCTIONAL_MESSAGE_PASSING_STACK_MODULE_SCHEMA_VERSION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STACKING_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_MATH_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_STACK_PREDICTION_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CLONES_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_DETACHES_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CASTS_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_MOVES_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_REGULARIZATION_REDUCTION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_AUDIT_RETENTION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_INDEPENDENT_REGISTRATION_PREFIX,
    FUNCTIONAL_MESSAGE_PASSING_STACK_FULLY_SHARED_REGISTRATION_PREFIX,
    derive_next_functional_message_passing_inputs,
    derive_next_layer_inputs,
    validate_rebound_functional_message_passing_inputs,
    validate_rebound_inputs,
    FunctionalMessagePassingStack,
    HazardConditionedFunctionalMessagePassingStack,
    FunctionalStack,
    MessagePassingStack,
    build_functional_message_passing_stack,
    build_stack,
    build_functional_message_passing_stack_from_factory,
    build_stack_from_factory,
    run_functional_message_passing_stack,
    run_stack,
    run_functional_message_passing_stack_complete,
    run_stack_complete,
)


# =============================================================================
# Public export inventory
# =============================================================================

__all__ = (
    "FUNCTIONAL_MESSAGE_PASSING_PACKAGE_API_VERSION",
    "schemas",
    "segment_ops",
    "relation_transforms",
    "edge_normalization",
    "aggregators",
    "relation_family_gate",
    "edge_attention",
    "message_builders",
    "layer",
    "stack",
    "AGGREGATION_OUTPUT_SCHEMA_VERSION",
    "EDGE_ATTENTION_OUTPUT_SCHEMA_VERSION",
    "EDGE_MESSAGE_OUTPUT_SCHEMA_VERSION",
    "EDGE_NORMALIZATION_OUTPUT_SCHEMA_VERSION",
    "FMP_INTERMEDIATES_SCHEMA_VERSION",
    "FMP_LAYER_OUTPUT_SCHEMA_VERSION",
    "FMP_NODE_STATE_SOURCE_LAYER_OUTPUT",
    "FMP_STACK_OUTPUT_SCHEMA_VERSION",
    "FUNCTIONAL_MESSAGE_PASSING_INPUT_SCHEMA_VERSION",
    "FUNCTIONAL_MESSAGE_PASSING_NODE_STATE_SCHEMA_VERSION",
    "RELATION_FAMILY_ALIGNMENT_SCHEMA_VERSION",
    "RELATION_GATE_OUTPUT_SCHEMA_VERSION",
    "RELATION_TRANSFORM_OUTPUT_SCHEMA_VERSION",
    "AggregationOutput",
    "FunctionalMessagePassingEdgeAttentionOutput",
    "FunctionalMessagePassingEdgeMessageOutput",
    "FunctionalMessagePassingInputs",
    "FunctionalMessagePassingIntermediates",
    "FunctionalMessagePassingLayerOutput",
    "FunctionalMessagePassingNodeState",
    "LegacyFunctionalMessagePassingStackOutput",
    "RelationFamilyAlignment",
    "FunctionalMessagePassingRelationGateOutput",
    "RelationTransformOutput",
    "StructuralEdgeNormalizationOutput",
    "SEGMENT_OPS_SCHEMA_VERSION",
    "SegmentMaxResult",
    "assert_grouped_softmax_normalized",
    "grouped_softmax",
    "grouped_softmax_sums",
    "segment_counts",
    "segment_max",
    "segment_mean",
    "segment_presence",
    "segment_sum",
    "validate_segment_ids",
    "PER_RELATION_TRANSFORM_SCHEMA_VERSION",
    "RELATION_TRANSFORMS_DISPATCHER_SCHEMA_VERSION",
    "SHARED_RELATION_TRANSFORM_SCHEMA_VERSION",
    "PerRelationTransform",
    "RelationTransforms",
    "SharedRelationTransform",
    "EDGE_NORMALIZATION_SCHEMA_VERSION",
    "EdgeNormalization",
    "AGGREGATOR_SCHEMA_VERSION",
    "Aggregator",
    "MessageAggregator",
    "GATE_ACTIVATION_OUTPUT_SCHEMA_VERSION",
    "GATE_NETWORK_OUTPUT_SCHEMA_VERSION",
    "RELATION_FAMILY_GATE_SCHEMA_VERSION",
    "RELATION_GATE_ACTIVATIONS_SCHEMA_VERSION",
    "RELATION_GATE_AXIS_SCHEMA_VERSION",
    "RELATION_GATE_NETWORK_SCHEMA_VERSION",
    "RELATION_PRIOR_CONTRIBUTION_SCHEMA_VERSION",
    "RELATION_PRIOR_INTEGRATION_SCHEMA_VERSION",
    "GateActivationOutput",
    "GateNetworkOutput",
    "RelationGateAxis",
    "RelationGateOutput",
    "RelationPriorContribution",
    "GateNetwork",
    "RelationGateNetwork",
    "RelationPriorBuilder",
    "RelationPriorContributionBuilder",
    "RelationPriorIntegration",
    "GateActivation",
    "RelationGateActivation",
    "apply_relation_gate_activation",
    "sigmoid_gate_activation",
    "RelationFamilyGate",
    "RelationGate",
    "ATTENTION_HEAD_REDUCTION_OUTPUT_SCHEMA_VERSION",
    "ATTENTION_NORMALIZATION_OUTPUT_SCHEMA_VERSION",
    "EDGE_ATTENTION_SCORE_OUTPUT_SCHEMA_VERSION",
    "EDGE_ATTENTION_SCORE_FUNCTIONS_SCHEMA_VERSION",
    "ATTENTION_NORMALIZATION_SCHEMA_VERSION",
    "ATTENTION_MULTIHEAD_SCHEMA_VERSION",
    "EDGE_ATTENTION_ORCHESTRATOR_SCHEMA_VERSION",
    "EDGE_ATTENTION_SCHEMA_MODES",
    "EDGE_ATTENTION_SCORE_MODES",
    "LEARNED_EDGE_ATTENTION_MODES",
    "IMPLEMENTED_ATTENTION_NORMALIZATION_MODES",
    "IMPLEMENTED_ATTENTION_HEAD_REDUCTIONS",
    "EDGE_ATTENTION_SCORE_FUNCTION_UNIFORM",
    "EDGE_ATTENTION_SCORE_FUNCTION_ADDITIVE",
    "EDGE_ATTENTION_INPUT_SOURCE_NODE_STATE",
    "EDGE_ATTENTION_INPUT_TARGET_NODE_STATE",
    "EDGE_ATTENTION_INPUT_TARGET_HAZARD_QUERY",
    "EDGE_ATTENTION_INPUT_EXACT_RELATION_EMBEDDING",
    "ATTENTION_GROUP_KEY_TARGET_NODE_EXACT_RELATION",
    "ATTENTION_GROUP_ID_FORMULA",
    "ATTENTION_HEAD_MEAN_FORMULA",
    "ATTENTION_HEAD_REDUCTION_INTERPRETATION",
    "EDGE_ATTENTION_GROUP_SEMANTICS",
    "EDGE_ATTENTION_OPERATION_ORDER",
    "EDGE_ATTENTION_SCIENTIFIC_INTERPRETATION",
    "DEFAULT_EDGE_ATTENTION_HIDDEN_DIM",
    "EdgeAttentionScoreOutput",
    "AttentionNormalizationOutput",
    "AttentionHeadReductionOutput",
    "EdgeAttentionOutput",
    "EdgeAttentionStages",
    "EdgeAttentionScoreFunction",
    "UniformEdgeAttentionScoreFunction",
    "UniformAttentionScoreFunction",
    "AdditiveEdgeAttentionScoreFunction",
    "AdditiveAttentionScoreFunction",
    "build_edge_attention_score_function",
    "build_attention_score_function",
    "AttentionNormalizer",
    "TargetNodeRelationAttentionNormalization",
    "AttentionNormalization",
    "EdgeAttentionNormalizer",
    "build_target_node_relation_group_ids",
    "build_target_node_relation_group_counts",
    "normalize_attention_logits",
    "normalize_edge_attention_scores",
    "apply_attention_normalization",
    "build_attention_normalizer",
    "build_edge_attention_normalizer",
    "attention_group_sums",
    "assert_attention_normalized",
    "maximum_attention_normalization_error",
    "AttentionHeadReducer",
    "MeanAttentionHeadReduction",
    "AttentionHeadReduction",
    "MultiheadAttentionReduction",
    "EdgeAttentionHeadReducer",
    "mean_reduce_attention_heads",
    "reduce_attention_heads",
    "reduce_normalized_attention_heads",
    "apply_attention_head_reduction",
    "build_attention_head_reducer",
    "build_edge_attention_head_reducer",
    "assert_reduced_attention_normalized",
    "maximum_reduced_attention_normalization_error",
    "attention_head_mean",
    "attention_head_variance",
    "attention_head_standard_deviation",
    "attention_head_range",
    "attention_head_mean_absolute_deviation",
    "maximum_attention_head_range",
    "mean_attention_head_standard_deviation",
    "head_disagreement_summary",
    "EdgeAttention",
    "EdgeAttentionModule",
    "FunctionalEdgeAttention",
    "HazardConditionedEdgeAttention",
    "assemble_edge_attention_output",
    "build_edge_attention",
    "build_edge_attention_module",
    "run_edge_attention",
    "MESSAGE_BUILDERS_PACKAGE_API_VERSION",
    "RESOLVED_MESSAGE_COEFFICIENTS_SCHEMA_VERSION",
    "MESSAGE_COMPOSITION_OUTPUT_SCHEMA_VERSION",
    "MESSAGE_SEMANTIC_EDGE_POLICY_IGNORE",
    "MESSAGE_SEMANTIC_EDGE_POLICY_USE_SOURCE_GRAPH",
    "CANONICAL_MESSAGE_SEMANTIC_EDGE_POLICIES",
    "IMPLEMENTED_MESSAGE_SEMANTIC_EDGE_POLICIES",
    "MESSAGE_FACTOR_STRUCTURAL_NORMALIZATION",
    "MESSAGE_FACTOR_RELATION_GATE",
    "MESSAGE_FACTOR_EDGE_ATTENTION",
    "MESSAGE_FACTOR_SEMANTIC_EDGE_WEIGHT",
    "MESSAGE_FACTOR_ORDER",
    "MESSAGE_DISABLED_FACTOR_POLICY",
    "MESSAGE_TRANSFORM_INPUT_LAYOUT",
    "MESSAGE_COMBINED_COEFFICIENT_FORMULA",
    "MESSAGE_COMPOSITION_FORMULA",
    "ResolvedMessageCoefficients",
    "MessageCoefficients",
    "MessageCompositionOutput",
    "EdgeMessageCompositionOutput",
    "MessageBuilderStages",
    "EdgeMessageOutput",
    "validate_message_builder_stage_chain",
    "validate_public_edge_message_output",
    "RELATION_STATE_GATHER_SCHEMA_VERSION",
    "RELATION_STATE_GATHER_OPERATION",
    "RELATION_STATE_GATHER_INPUT_LAYOUT",
    "RELATION_STATE_GATHER_OUTPUT_LAYOUT",
    "RELATION_STATE_GATHER_OWNER",
    "RELATION_STATE_GATHER_INDEXING_OWNED_HERE",
    "RELATION_STATE_GATHER_ZERO_COPY_REQUIRED",
    "RELATION_STATE_GATHER_PARAMETER_FREE",
    "RELATION_STATE_GATHER_OPERATION_ORDER",
    "relation_state_gather_architecture_dict",
    "relation_state_gather_architecture_fingerprint",
    "validate_edge_aligned_relation_state",
    "assert_zero_copy_relation_state",
    "resolve_edge_aligned_relation_state",
    "resolve_relation_state",
    "gather_relation_state",
    "relation_state_gather_diagnostic_summary",
    "validate_relation_state_gather_contract",
    "RelationStateGather",
    "RelationStateResolver",
    "EdgeAlignedRelationStateResolver",
    "build_relation_state_gather",
    "build_relation_state_resolver",
    "MESSAGE_COEFFICIENT_RESOLUTION_SCHEMA_VERSION",
    "MESSAGE_COEFFICIENT_RESOLUTION_OPERATION_ORDER",
    "MESSAGE_COEFFICIENT_RESOLUTION_INTERPRETATION",
    "MESSAGE_COEFFICIENT_RESOLUTION_PARAMETER_FREE",
    "MESSAGE_COEFFICIENT_RESOLUTION_BUFFER_FREE",
    "OptionalFactorResolution",
    "SemanticFactorResolution",
    "resolve_structural_normalization_factor",
    "resolve_relation_gate_factor",
    "resolve_edge_attention_factor",
    "resolve_semantic_edge_factor",
    "combine_message_coefficients",
    "coefficient_resolution_architecture_dict",
    "coefficient_resolution_architecture_fingerprint",
    "resolve_message_coefficients",
    "resolve_edge_message_coefficients",
    "validate_resolved_message_coefficients",
    "message_coefficient_diagnostic_summary",
    "MessageCoefficientResolver",
    "CoefficientResolver",
    "EdgeMessageCoefficientResolver",
    "build_message_coefficient_resolver",
    "build_coefficient_resolver",
    "MESSAGE_COMPOSER_SCHEMA_VERSION",
    "MESSAGE_COMPOSER_OPERATION",
    "MESSAGE_COMPOSER_OPERATION_ORDER",
    "MESSAGE_COMPOSER_INPUT_STATE_LAYOUT",
    "MESSAGE_COMPOSER_INPUT_COEFFICIENT_LAYOUT",
    "MESSAGE_COMPOSER_OUTPUT_LAYOUT",
    "MESSAGE_COMPOSER_BROADCAST_AXIS",
    "MESSAGE_COMPOSER_PARAMETER_FREE",
    "MESSAGE_COMPOSER_BUFFER_FREE",
    "MESSAGE_COMPOSER_AGGREGATION_OWNED_HERE",
    "message_composer_architecture_dict",
    "message_composer_architecture_fingerprint",
    "compose_edge_message_tensor",
    "compose_message_vectors",
    "compose_message_output",
    "compose_edge_messages",
    "validate_message_composition_output",
    "message_composition_diagnostic_summary",
    "EdgeMessageComposer",
    "MessageComposer",
    "FunctionalMessageComposer",
    "build_edge_message_composer",
    "build_message_composer",
    "MESSAGE_BUILDER_DIAGNOSTICS_SCHEMA_VERSION",
    "MESSAGE_BUILDER_DIAGNOSTICS_INTERPRETATION",
    "MESSAGE_BUILDER_DIAGNOSTICS_OPERATION_ORDER",
    "MESSAGE_BUILDER_DIAGNOSTICS_PARAMETER_FREE",
    "MESSAGE_BUILDER_DIAGNOSTICS_BUFFER_FREE",
    "MESSAGE_BUILDER_DIAGNOSTIC_SECTION_STAGE_SUMMARIES",
    "MESSAGE_BUILDER_DIAGNOSTIC_SECTION_GLOBAL",
    "MESSAGE_BUILDER_DIAGNOSTIC_SECTION_BY_RELATION",
    "MESSAGE_BUILDER_DIAGNOSTIC_SECTION_BY_GRAPH",
    "MESSAGE_BUILDER_DIAGNOSTIC_SECTION_LINEAGE",
    "MESSAGE_BUILDER_DIAGNOSTIC_SECTION_ALERTS",
    "MESSAGE_BUILDER_DIAGNOSTIC_REQUIRED_SECTIONS",
    "MessageBuilderDiagnosticThresholds",
    "DEFAULT_MESSAGE_BUILDER_DIAGNOSTIC_THRESHOLDS",
    "message_builder_scalar_tensor_statistics",
    "edge_vector_norm_statistics",
    "factor_statistics",
    "exact_relation_diagnostics",
    "message_builder_graph_batch_diagnostics",
    "message_builder_lineage_summary",
    "derive_message_builder_alerts",
    "message_builder_diagnostics_architecture_dict",
    "message_builder_diagnostics_architecture_fingerprint",
    "build_message_builder_diagnostic_report",
    "message_builder_diagnostic_report",
    "build_public_edge_message_diagnostic_report",
    "public_edge_message_diagnostic_report",
    "diagnostic_report_fingerprint",
    "validate_message_builder_diagnostic_report",
    "MessageBuilderDiagnostics",
    "MessageDiagnostics",
    "EdgeMessageDiagnostics",
    "build_message_builder_diagnostics",
    "build_edge_message_diagnostics",
    "MESSAGE_BUILDERS_ORCHESTRATOR_SCHEMA_VERSION",
    "MESSAGE_BUILDERS_OPERATION_ORDER",
    "MESSAGE_BUILDERS_SCIENTIFIC_INTERPRETATION",
    "MESSAGE_BUILDERS_DISABLED_GATE_REPRESENTATION",
    "MESSAGE_BUILDERS_DISABLED_ATTENTION_REPRESENTATION",
    "MESSAGE_BUILDERS_PARAMETER_FREE",
    "MESSAGE_BUILDERS_BUFFER_FREE",
    "MESSAGE_BUILDERS_AGGREGATION_OWNED_HERE",
    "MESSAGE_BUILDERS_OUTPUT_SCHEMA",
    "MessageBuilderRun",
    "MessageBuilderRunWithDiagnostics",
    "assemble_edge_message_output",
    "validate_complete_message_builder_run",
    "EdgeMessageBuilder",
    "MessageBuilder",
    "FunctionalMessageBuilder",
    "FunctionalEdgeMessageBuilder",
    "build_edge_message_builder",
    "build_message_builder",
    "build_message_builders",
    "run_edge_message_builder",
    "run_message_builder",
    "run_edge_message_builder_stages",
    "run_message_builder_stages",
    "LAYER_PACKAGE_API_VERSION",
    "LAYER_INPUTS_SCHEMA_VERSION",
    "LAYER_TRACE_POLICY_SCHEMA_VERSION",
    "LAYER_RESIDUAL_UPDATE_SCHEMA_VERSION",
    "LAYER_NORMALIZATION_OUTPUT_SCHEMA_VERSION",
    "LAYER_INTERMEDIATE_TRACE_SCHEMA_VERSION",
    "LAYER_COMPUTATION_OUTPUT_SCHEMA_VERSION",
    "LAYER_TRACE_NONE",
    "LAYER_TRACE_NODE",
    "LAYER_TRACE_FULL",
    "CANONICAL_LAYER_TRACE_MODES",
    "V2_0_IMPLEMENTED_LAYER_TRACE_MODES",
    "LayerTracePolicy",
    "LAYER_RESIDUAL_DISABLED",
    "LAYER_RESIDUAL_ADDITIVE",
    "CANONICAL_LAYER_RESIDUAL_MODES",
    "V2_0_IMPLEMENTED_LAYER_RESIDUAL_MODES",
    "LAYER_NORMALIZATION_NONE",
    "LAYER_NORMALIZATION_LAYER_NORM",
    "CANONICAL_LAYER_NORMALIZATION_MODES",
    "V2_0_IMPLEMENTED_LAYER_NORMALIZATION_MODES",
    "LAYER_NORMALIZATION_PRE_RESIDUAL",
    "LAYER_NORMALIZATION_POST_RESIDUAL",
    "CANONICAL_LAYER_NORMALIZATION_POSITIONS",
    "V2_0_IMPLEMENTED_LAYER_NORMALIZATION_POSITIONS",
    "LAYER_UPDATE_BRANCH_FORMULA",
    "LAYER_ADDITIVE_RESIDUAL_FORMULA",
    "LAYER_DISABLED_RESIDUAL_FORMULA",
    "LAYER_POST_NORMALIZATION_FORMULA",
    "LAYER_INPUT_LAYOUT",
    "LAYER_AGGREGATE_LAYOUT",
    "LAYER_OUTPUT_LAYOUT",
    "LAYER_SCIENTIFIC_INTERPRETATION",
    "FunctionalMessagePassingLayerInputs",
    "LayerInputs",
    "LayerResidualUpdateOutput",
    "ResidualUpdateOutput",
    "LayerNormalizationOutput",
    "NormalizationOutput",
    "FunctionalMessagePassingLayerTrace",
    "LayerTrace",
    "LayerComputationOutput",
    "FunctionalMessagePassingLayerComputation",
    "FunctionalMessagePassingLayerStages",
    "LayerStages",
    "validate_layer_stage_chain",
    "build_public_layer_intermediates",
    "validate_public_layer_output",
    "layer_schema_architecture_dict",
    "layer_schema_architecture_fingerprint",
    "LAYER_RESIDUAL_UPDATER_SCHEMA_VERSION",
    "LAYER_RESIDUAL_UPDATER_OPERATION",
    "LAYER_RESIDUAL_UPDATER_OPERATION_ORDER",
    "LAYER_RESIDUAL_UPDATER_PARAMETER_FREE",
    "LAYER_RESIDUAL_UPDATER_BUFFER_FREE",
    "LAYER_RESIDUAL_UPDATER_PROJECTION_OWNED_HERE",
    "LAYER_RESIDUAL_UPDATER_AGGREGATION_OWNED_HERE",
    "LAYER_RESIDUAL_UPDATER_NORMALIZATION_OWNED_HERE",
    "LAYER_DROPOUT_SEMANTICS",
    "LAYER_DISABLED_DROPOUT_IDENTITY_POLICY",
    "LAYER_DISABLED_RESIDUAL_IDENTITY_POLICY",
    "residual_mode_from_enabled",
    "residual_enabled_from_mode",
    "layer_residual_updater_architecture_dict",
    "layer_residual_updater_architecture_fingerprint",
    "apply_layer_update_dropout",
    "apply_update_dropout",
    "apply_layer_residual",
    "apply_residual",
    "build_layer_residual_update_output",
    "apply_layer_residual_update",
    "resolve_layer_residual_update",
    "validate_layer_residual_update_output",
    "layer_residual_update_diagnostic_summary",
    "LayerResidualUpdater",
    "ResidualUpdater",
    "FunctionalResidualUpdater",
    "MessagePassingResidualUpdater",
    "build_layer_residual_updater",
    "build_residual_updater",
    "build_layer_residual_updater_from_flags",
    "build_residual_updater_from_flags",
    "LAYER_NORMALIZER_SCHEMA_VERSION",
    "LAYER_NORMALIZER_OPERATION",
    "LAYER_NORMALIZER_OPERATION_ORDER",
    "LAYER_NORMALIZER_NORMALIZED_AXIS",
    "LAYER_NORMALIZER_STATISTIC_SCOPE",
    "LAYER_NORMALIZER_VARIANCE_ESTIMATOR",
    "LAYER_NORMALIZER_AGGREGATION_OWNED_HERE",
    "LAYER_NORMALIZER_DROPOUT_OWNED_HERE",
    "LAYER_NORMALIZER_RESIDUAL_OWNED_HERE",
    "LAYER_NORMALIZER_MULTI_LAYER_ITERATION_OWNED_HERE",
    "LAYER_DISABLED_NORMALIZATION_IDENTITY_POLICY",
    "LAYER_NORMALIZER_DEFAULT_EPSILON",
    "LAYER_NORMALIZER_DEFAULT_ELEMENTWISE_AFFINE",
    "LAYER_NORMALIZER_DEFAULT_BIAS_ENABLED",
    "normalization_mode_from_enabled",
    "normalization_enabled_from_mode",
    "layer_normalizer_architecture_dict",
    "layer_normalizer_architecture_fingerprint",
    "apply_layer_normalization",
    "apply_normalization",
    "build_layer_normalization_output",
    "normalize_layer_state",
    "resolve_layer_normalization",
    "validate_layer_normalization_output",
    "layer_normalization_diagnostic_summary",
    "LayerNormalizer",
    "FunctionalLayerNormalizer",
    "MessagePassingLayerNormalizer",
    "PostResidualLayerNormalizer",
    "build_layer_normalizer",
    "build_normalizer",
    "build_layer_normalizer_from_flag",
    "build_normalizer_from_flag",
    "LAYER_DIAGNOSTICS_SCHEMA_VERSION",
    "LAYER_DIAGNOSTICS_INTERPRETATION",
    "LAYER_DIAGNOSTICS_OPERATION_ORDER",
    "LAYER_DIAGNOSTICS_PARAMETER_FREE",
    "LAYER_DIAGNOSTICS_BUFFER_FREE",
    "LAYER_DIAGNOSTICS_IMPLICIT_FORWARD_EXECUTION",
    "LAYER_DIAGNOSTIC_SECTION_STAGE_SUMMARIES",
    "LAYER_DIAGNOSTIC_SECTION_GLOBAL",
    "LAYER_DIAGNOSTIC_SECTION_BY_GRAPH",
    "LAYER_DIAGNOSTIC_SECTION_TRACE",
    "LAYER_DIAGNOSTIC_SECTION_REGULARIZATION",
    "LAYER_DIAGNOSTIC_SECTION_LINEAGE",
    "LAYER_DIAGNOSTIC_SECTION_ALERTS",
    "LAYER_DIAGNOSTIC_REQUIRED_SECTIONS",
    "LayerDiagnosticThresholds",
    "DEFAULT_LAYER_DIAGNOSTIC_THRESHOLDS",
    "layer_scalar_tensor_statistics",
    "matrix_statistics",
    "state_transition_statistics",
    "incoming_edge_count_statistics",
    "aggregation_diagnostic_summary",
    "layer_graph_batch_diagnostics",
    "layer_trace_diagnostic_summary",
    "layer_lineage_summary",
    "regularization_diagnostic_summary",
    "derive_layer_alerts",
    "layer_diagnostics_architecture_dict",
    "layer_diagnostics_architecture_fingerprint",
    "build_layer_diagnostic_report",
    "layer_diagnostic_report",
    "build_public_layer_diagnostic_report",
    "public_layer_diagnostic_report",
    "layer_diagnostic_report_fingerprint",
    "validate_layer_diagnostic_report",
    "LayerDiagnostics",
    "FunctionalLayerDiagnostics",
    "MessagePassingLayerDiagnostics",
    "build_layer_diagnostics",
    "build_functional_layer_diagnostics",
    "build_message_passing_layer_diagnostics",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_SCHEMA_VERSION",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_OPERATION_ORDER",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_SCIENTIFIC_INTERPRETATION",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_OUTPUT_SCHEMA",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_AGGREGATION_ORCHESTRATED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_AGGREGATION_MATH_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_STACKING_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_PREDICTION_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_DISABLED_GATE_REPRESENTATION",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_DISABLED_ATTENTION_REPRESENTATION",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_UNIFORM_ATTENTION_REPRESENTATION",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_TRACE_AFFECTS_NUMERICS",
    "FUNCTIONAL_MESSAGE_PASSING_LAYER_DIAGNOSTICS_AFFECT_NUMERICS",
    "FunctionalMessagePassingLayerEdgeStages",
    "LayerEdgeStages",
    "FunctionalMessagePassingLayerNodeStages",
    "LayerNodeStages",
    "FunctionalMessagePassingLayerRun",
    "LayerRun",
    "FunctionalMessagePassingLayerRunWithDiagnostics",
    "LayerRunWithDiagnostics",
    "assemble_functional_message_passing_layer_output",
    "validate_functional_message_passing_layer_run",
    "FunctionalMessagePassingLayer",
    "HazardConditionedFunctionalMessagePassingLayer",
    "FunctionalLayer",
    "MessagePassingLayer",
    "build_functional_message_passing_layer",
    "build_layer",
    "build_functional_message_passing_layer_from_config",
    "build_layer_from_config",
    "run_functional_message_passing_layer",
    "run_layer",
    "run_functional_message_passing_layer_complete",
    "run_layer_complete",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_SCHEMA_VERSION",
    "STACK_INPUTS_SCHEMA_VERSION",
    "STACK_DEPTH_RECORD_SCHEMA_VERSION",
    "STACK_TRACE_SCHEMA_VERSION",
    "STACK_COMPUTATION_OUTPUT_SCHEMA_VERSION",
    "STACK_PUBLIC_OUTPUT_SCHEMA_VERSION",
    "STACK_RUN_SCHEMA_VERSION",
    "STACK_RUN_WITH_DIAGNOSTICS_SCHEMA_VERSION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_OPERATION_ORDER",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_SCIENTIFIC_INTERPRETATION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_OUTPUT_SCHEMA",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_REIMPLEMENTS_LAYER_MATH",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_RETENTION_AFFECTS_NUMERICS",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_TRACE_AFFECTS_NUMERICS",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_DIAGNOSTICS_AFFECT_NUMERICS",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_HIDDEN_WIDTH_CHANGES_SUPPORTED",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_ZERO_LAYER_SUPPORTED",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_PARTIAL_SHARING_SUPPORTED",
    "expected_retained_layer_indices",
    "FunctionalMessagePassingStackInputs",
    "StackInputs",
    "FunctionalMessagePassingStackDepthRecord",
    "StackDepthRecord",
    "FunctionalMessagePassingStackTrace",
    "StackTrace",
    "FunctionalMessagePassingStackComputationOutput",
    "StackComputationOutput",
    "FunctionalMessagePassingStackOutput",
    "StackOutput",
    "FunctionalMessagePassingStackRun",
    "StackRun",
    "FunctionalMessagePassingStackRunWithDiagnostics",
    "StackRunWithDiagnostics",
    "assemble_functional_message_passing_stack_output",
    "assemble_stack_output",
    "validate_public_stack_output",
    "validate_functional_message_passing_stack_run",
    "validate_stack_run",
    "STACK_SHARING_POLICY_SCHEMA_VERSION",
    "STACK_LAYER_SHARING_PLAN_SCHEMA_VERSION",
    "STACK_SHARING_POLICY_AFFECTS_NUMERICAL_ARCHITECTURE",
    "STACK_SHARING_POLICY_AFFECTS_PARAMETER_OWNERSHIP",
    "STACK_SHARING_POLICY_AFFECTS_TRACE_DETAIL",
    "STACK_SHARING_POLICY_AFFECTS_OUTPUT_RETENTION",
    "STACK_SHARING_POLICY_AFFECTS_DIAGNOSTICS",
    "STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_MODULES",
    "STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_PARAMETERS",
    "STACK_SHARING_FULLY_SHARED_REQUIRES_EXACT_MODULE_REUSE",
    "STACK_SHARING_PARTIAL_SUPPORTED",
    "STACK_SHARING_SCIENTIFIC_INTERPRETATION",
    "INDEPENDENT_LAYER_STATE_DICT_PREFIX",
    "FULLY_SHARED_LAYER_STATE_DICT_PREFIX",
    "normalize_stack_sharing_policy",
    "normalize_sharing_policy",
    "assert_stack_sharing_policy_implemented",
    "is_independent_stack_sharing_policy",
    "is_fully_shared_stack_sharing_policy",
    "StackSharingPolicy",
    "SharingPolicy",
    "resolve_stack_sharing_policy",
    "resolve_sharing_policy",
    "StackLayerSharingPlan",
    "LayerSharingPlan",
    "build_independent_stack_layer_sharing_plan",
    "build_fully_shared_stack_layer_sharing_plan",
    "build_stack_layer_sharing_plan",
    "build_layer_sharing_plan",
    "build_stack_layer_sharing_plan_from_factory",
    "build_layer_sharing_plan_from_factory",
    "validate_stack_layer_sharing_plan",
    "validate_layer_sharing_plan",
    "layer_for_stack_depth",
    "STACK_RETENTION_POLICY_SCHEMA_VERSION",
    "STACK_TRACE_POLICY_SCHEMA_VERSION",
    "STACK_TRACE_DECISION_SCHEMA_VERSION",
    "STACK_RETENTION_AFFECTS_NUMERICAL_RESULTS",
    "STACK_LAYER_TRACE_AFFECTS_NUMERICAL_RESULTS",
    "STACK_AUDIT_MODE_AFFECTS_NUMERICAL_RESULTS",
    "STACK_RETENTION_NONE_RETAINS_FINAL_LAYER",
    "STACK_RETENTION_FINAL_LAYER_RETAINS_FINAL_LAYER",
    "STACK_RETENTION_ALL_LAYERS_RETAINS_FINAL_LAYER",
    "STACK_RETENTION_POLICY_IS_OUTPUT_CONTRACT",
    "STACK_LAYER_TRACE_POLICY_IS_OUTPUT_CONTRACT",
    "STACK_TRACE_POLICY_IS_NUMERICAL_ARCHITECTURE",
    "STACK_TRACE_POLICY_SCIENTIFIC_INTERPRETATION",
    "normalize_stack_retention_policy",
    "normalize_retention_policy",
    "assert_stack_retention_policy_implemented",
    "resolve_stack_retention_policy",
    "resolve_retention_policy",
    "is_no_stack_retention",
    "is_final_layer_stack_retention",
    "is_all_layers_stack_retention",
    "StackRetentionPolicy",
    "RetentionPolicy",
    "StackTraceDecision",
    "TraceDecision",
    "StackTracePolicy",
    "TracePolicy",
    "resolve_stack_trace_policy",
    "resolve_trace_policy",
    "build_stack_trace_policy",
    "build_trace_policy",
    "build_stack_trace_decisions",
    "build_trace_decisions",
    "validate_stack_trace_decisions",
    "validate_trace_decisions",
    "validate_retained_layer_indices",
    "assert_stack_trace_policy_matches",
    "stack_trace_policies_are_numerically_equivalent",
    "STACK_DIAGNOSTIC_THRESHOLDS_SCHEMA_VERSION",
    "STACK_DEPTH_DIAGNOSTIC_SCHEMA_VERSION",
    "STACK_DIAGNOSTIC_REPORT_SCHEMA_VERSION",
    "STACK_DIAGNOSTICS_SCHEMA_VERSION",
    "STACK_DIAGNOSTICS_AFFECT_NUMERICAL_RESULTS",
    "STACK_DIAGNOSTICS_RETAIN_AUTOGRAD_REFERENCES",
    "STACK_DIAGNOSTICS_RETURN_TENSORS",
    "STACK_DIAGNOSTICS_ESTABLISH_CAUSALITY",
    "STACK_DIAGNOSTICS_ESTABLISH_FAITHFULNESS",
    "STACK_DIAGNOSTICS_ESTABLISH_CALIBRATION",
    "STACK_DIAGNOSTICS_ESTABLISH_IDENTIFIABILITY",
    "STACK_DIAGNOSTIC_DEPTH_SOURCE_AUDIT_TRACE",
    "STACK_DIAGNOSTIC_DEPTH_SOURCE_RETAINED_OUTPUT",
    "STACK_DIAGNOSTIC_DEPTH_SOURCE_UNAVAILABLE",
    "CANONICAL_STACK_DIAGNOSTIC_DEPTH_SOURCES",
    "STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_COLLAPSE",
    "STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_EXPLOSION",
    "STACK_DIAGNOSTIC_ALERT_TOTAL_UPDATE_LARGE",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_COLLAPSE",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_EXPLOSION",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_LARGE",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_TINY",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_DIRECTION_REVERSAL",
    "STACK_DIAGNOSTIC_ALERT_INCOMPLETE_DEPTH_COVERAGE",
    "STACK_DIAGNOSTIC_ALERT_SHARED_PARAMETER_DRIFT",
    "STACK_DIAGNOSTIC_ALERT_SHARED_ARCHITECTURE_DRIFT",
    "STACK_DIAGNOSTIC_SCIENTIFIC_CLAIMS",
    "StackDiagnosticThresholds",
    "DiagnosticThresholds",
    "StackDepthDiagnostic",
    "DepthDiagnostic",
    "FunctionalMessagePassingStackDiagnosticReport",
    "StackDiagnosticReport",
    "build_functional_message_passing_stack_diagnostic_report",
    "build_stack_diagnostic_report",
    "build_diagnostic_report",
    "validate_functional_message_passing_stack_diagnostic_report",
    "validate_stack_diagnostic_report",
    "validate_diagnostic_report",
    "FunctionalMessagePassingStackDiagnostics",
    "StackDiagnostics",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_MODULE_SCHEMA_VERSION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STACKING_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_MATH_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_PREDICTION_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CLONES_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_DETACHES_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CASTS_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_MOVES_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_REGULARIZATION_REDUCTION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_AUDIT_RETENTION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_INDEPENDENT_REGISTRATION_PREFIX",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_FULLY_SHARED_REGISTRATION_PREFIX",
    "derive_next_functional_message_passing_inputs",
    "derive_next_layer_inputs",
    "validate_rebound_functional_message_passing_inputs",
    "validate_rebound_inputs",
    "FunctionalMessagePassingStack",
    "HazardConditionedFunctionalMessagePassingStack",
    "FunctionalStack",
    "MessagePassingStack",
    "build_functional_message_passing_stack",
    "build_stack",
    "build_functional_message_passing_stack_from_factory",
    "build_stack_from_factory",
    "run_functional_message_passing_stack",
    "run_stack",
    "run_functional_message_passing_stack_complete",
    "run_stack_complete",
)
