"""
Public API for stacked hazard-conditioned functional message passing.

Target path:
    urban_resilience_models/
        v2_hazard_conditioned_functional_ugnn/
            functional_message_passing/
                stack/
                    __init__.py

The stack package composes complete ``FunctionalMessagePassingLayer`` modules
without reimplementing one-layer message-passing mathematics.

The public surface exposes:

- immutable stack inputs, depth records, audit traces, outputs, and runs;
- independent and fully shared parameter-ownership policies;
- public-output retention and one-layer trace-detail policies;
- explicit tensor-free diagnostics;
- immutable depth-wise node-state rebinding;
- the complete ``FunctionalMessagePassingStack`` module;
- construction, execution, assembly, and validation helpers;
- compact aliases for common call sites.

Importing this package does not construct model components, execute a stack,
mutate registries, enable diagnostics, or retain audit traces.

Boundary
-------------------
Stack outputs, gates, attention values, regularization terms, retained traces,
and diagnostic summaries are descriptive model quantities. They do not by
themselves establish causal influence, explanation faithfulness, calibrated
uncertainty, counterfactual validity, or mechanistic identifiability.
"""


# =============================================================================
# Immutable schemas and run contracts
# =============================================================================

from .schemas import (
    FUNCTIONAL_MESSAGE_PASSING_STACK_SCHEMA_VERSION,
    STACK_INPUTS_SCHEMA_VERSION,
    STACK_DEPTH_RECORD_SCHEMA_VERSION,
    STACK_TRACE_SCHEMA_VERSION,
    STACK_COMPUTATION_OUTPUT_SCHEMA_VERSION,
    STACK_PUBLIC_OUTPUT_SCHEMA_VERSION,
    STACK_RUN_SCHEMA_VERSION,
    STACK_RUN_WITH_DIAGNOSTICS_SCHEMA_VERSION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_OPERATION_ORDER,
    FUNCTIONAL_MESSAGE_PASSING_STACK_SCIENTIFIC_INTERPRETATION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_OUTPUT_SCHEMA,
    FUNCTIONAL_MESSAGE_PASSING_STACK_REIMPLEMENTS_LAYER_MATH,
    FUNCTIONAL_MESSAGE_PASSING_STACK_RETENTION_AFFECTS_NUMERICS,
    FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_TRACE_AFFECTS_NUMERICS,
    FUNCTIONAL_MESSAGE_PASSING_STACK_DIAGNOSTICS_AFFECT_NUMERICS,
    FUNCTIONAL_MESSAGE_PASSING_STACK_HIDDEN_WIDTH_CHANGES_SUPPORTED,
    FUNCTIONAL_MESSAGE_PASSING_STACK_ZERO_LAYER_SUPPORTED,
    FUNCTIONAL_MESSAGE_PASSING_STACK_PARTIAL_SHARING_SUPPORTED,
    expected_retained_layer_indices,
    FunctionalMessagePassingStackInputs,
    StackInputs,
    FunctionalMessagePassingStackDepthRecord,
    StackDepthRecord,
    FunctionalMessagePassingStackTrace,
    StackTrace,
    FunctionalMessagePassingStackComputationOutput,
    StackComputationOutput,
    FunctionalMessagePassingStackOutput,
    StackOutput,
    FunctionalMessagePassingStackRun,
    StackRun,
    FunctionalMessagePassingStackRunWithDiagnostics,
    StackRunWithDiagnostics,
    assemble_functional_message_passing_stack_output,
    assemble_stack_output,
    validate_public_stack_output,
    validate_functional_message_passing_stack_run,
    validate_stack_run,
)


# =============================================================================
# Parameter-sharing policy
# =============================================================================

from .sharing_policy import (
    STACK_SHARING_POLICY_SCHEMA_VERSION,
    STACK_LAYER_SHARING_PLAN_SCHEMA_VERSION,
    STACK_SHARING_POLICY_AFFECTS_NUMERICAL_ARCHITECTURE,
    STACK_SHARING_POLICY_AFFECTS_PARAMETER_OWNERSHIP,
    STACK_SHARING_POLICY_AFFECTS_TRACE_DETAIL,
    STACK_SHARING_POLICY_AFFECTS_OUTPUT_RETENTION,
    STACK_SHARING_POLICY_AFFECTS_DIAGNOSTICS,
    STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_MODULES,
    STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_PARAMETERS,
    STACK_SHARING_FULLY_SHARED_REQUIRES_EXACT_MODULE_REUSE,
    STACK_SHARING_PARTIAL_SUPPORTED,
    STACK_SHARING_SCIENTIFIC_INTERPRETATION,
    INDEPENDENT_LAYER_STATE_DICT_PREFIX,
    FULLY_SHARED_LAYER_STATE_DICT_PREFIX,
    normalize_stack_sharing_policy,
    normalize_sharing_policy,
    assert_stack_sharing_policy_implemented,
    is_independent_stack_sharing_policy,
    is_fully_shared_stack_sharing_policy,
    StackSharingPolicy,
    SharingPolicy,
    resolve_stack_sharing_policy,
    resolve_sharing_policy,
    StackLayerSharingPlan,
    LayerSharingPlan,
    build_independent_stack_layer_sharing_plan,
    build_fully_shared_stack_layer_sharing_plan,
    build_stack_layer_sharing_plan,
    build_layer_sharing_plan,
    build_stack_layer_sharing_plan_from_factory,
    build_layer_sharing_plan_from_factory,
    validate_stack_layer_sharing_plan,
    validate_layer_sharing_plan,
    layer_for_stack_depth,
)


# =============================================================================
# Trace-detail and output-retention policy
# =============================================================================

from .trace_policy import (
    STACK_RETENTION_POLICY_SCHEMA_VERSION,
    STACK_TRACE_POLICY_SCHEMA_VERSION,
    STACK_TRACE_DECISION_SCHEMA_VERSION,
    STACK_RETENTION_AFFECTS_NUMERICAL_RESULTS,
    STACK_LAYER_TRACE_AFFECTS_NUMERICAL_RESULTS,
    STACK_AUDIT_MODE_AFFECTS_NUMERICAL_RESULTS,
    STACK_RETENTION_NONE_RETAINS_FINAL_LAYER,
    STACK_RETENTION_FINAL_LAYER_RETAINS_FINAL_LAYER,
    STACK_RETENTION_ALL_LAYERS_RETAINS_FINAL_LAYER,
    STACK_RETENTION_POLICY_IS_OUTPUT_CONTRACT,
    STACK_LAYER_TRACE_POLICY_IS_OUTPUT_CONTRACT,
    STACK_TRACE_POLICY_IS_NUMERICAL_ARCHITECTURE,
    STACK_TRACE_POLICY_SCIENTIFIC_INTERPRETATION,
    normalize_stack_retention_policy,
    normalize_retention_policy,
    assert_stack_retention_policy_implemented,
    resolve_stack_retention_policy,
    resolve_retention_policy,
    is_no_stack_retention,
    is_final_layer_stack_retention,
    is_all_layers_stack_retention,
    StackRetentionPolicy,
    RetentionPolicy,
    StackTraceDecision,
    TraceDecision,
    StackTracePolicy,
    TracePolicy,
    resolve_stack_trace_policy,
    resolve_trace_policy,
    build_stack_trace_policy,
    build_trace_policy,
    build_stack_trace_decisions,
    build_trace_decisions,
    validate_stack_trace_decisions,
    validate_trace_decisions,
    validate_retained_layer_indices,
    assert_stack_trace_policy_matches,
    stack_trace_policies_are_numerically_equivalent,
)


# =============================================================================
# Explicit tensor-free diagnostics
# =============================================================================

from .diagnostics import (
    STACK_DIAGNOSTIC_THRESHOLDS_SCHEMA_VERSION,
    STACK_DEPTH_DIAGNOSTIC_SCHEMA_VERSION,
    STACK_DIAGNOSTIC_REPORT_SCHEMA_VERSION,
    STACK_DIAGNOSTICS_SCHEMA_VERSION,
    STACK_DIAGNOSTICS_AFFECT_NUMERICAL_RESULTS,
    STACK_DIAGNOSTICS_RETAIN_AUTOGRAD_REFERENCES,
    STACK_DIAGNOSTICS_RETURN_TENSORS,
    STACK_DIAGNOSTICS_ESTABLISH_CAUSALITY,
    STACK_DIAGNOSTICS_ESTABLISH_FAITHFULNESS,
    STACK_DIAGNOSTICS_ESTABLISH_CALIBRATION,
    STACK_DIAGNOSTICS_ESTABLISH_IDENTIFIABILITY,
    STACK_DIAGNOSTIC_DEPTH_SOURCE_AUDIT_TRACE,
    STACK_DIAGNOSTIC_DEPTH_SOURCE_RETAINED_OUTPUT,
    STACK_DIAGNOSTIC_DEPTH_SOURCE_UNAVAILABLE,
    CANONICAL_STACK_DIAGNOSTIC_DEPTH_SOURCES,
    STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_COLLAPSE,
    STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_EXPLOSION,
    STACK_DIAGNOSTIC_ALERT_TOTAL_UPDATE_LARGE,
    STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_COLLAPSE,
    STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_EXPLOSION,
    STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_LARGE,
    STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_TINY,
    STACK_DIAGNOSTIC_ALERT_DEPTH_DIRECTION_REVERSAL,
    STACK_DIAGNOSTIC_ALERT_INCOMPLETE_DEPTH_COVERAGE,
    STACK_DIAGNOSTIC_ALERT_SHARED_PARAMETER_DRIFT,
    STACK_DIAGNOSTIC_ALERT_SHARED_ARCHITECTURE_DRIFT,
    STACK_DIAGNOSTIC_SCIENTIFIC_CLAIMS,
    StackDiagnosticThresholds,
    DiagnosticThresholds,
    StackDepthDiagnostic,
    DepthDiagnostic,
    FunctionalMessagePassingStackDiagnosticReport,
    StackDiagnosticReport,
    build_functional_message_passing_stack_diagnostic_report,
    build_stack_diagnostic_report,
    build_diagnostic_report,
    validate_functional_message_passing_stack_diagnostic_report,
    validate_stack_diagnostic_report,
    validate_diagnostic_report,
    FunctionalMessagePassingStackDiagnostics,
    StackDiagnostics,
)


# =============================================================================
# Complete stack orchestration
# =============================================================================

from .stack import (
    FUNCTIONAL_MESSAGE_PASSING_STACK_MODULE_SCHEMA_VERSION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STACKING_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_MATH_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_STACK_PREDICTION_OWNED_HERE,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CLONES_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_DETACHES_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CASTS_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_MOVES_TENSOR,
    FUNCTIONAL_MESSAGE_PASSING_STACK_REGULARIZATION_REDUCTION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_AUDIT_RETENTION,
    FUNCTIONAL_MESSAGE_PASSING_STACK_INDEPENDENT_REGISTRATION_PREFIX,
    FUNCTIONAL_MESSAGE_PASSING_STACK_FULLY_SHARED_REGISTRATION_PREFIX,
    derive_next_functional_message_passing_inputs,
    derive_next_layer_inputs,
    validate_rebound_functional_message_passing_inputs,
    validate_rebound_inputs,
    FunctionalMessagePassingStack,
    HazardConditionedFunctionalMessagePassingStack,
    FunctionalStack,
    MessagePassingStack,
    build_functional_message_passing_stack,
    build_stack,
    build_functional_message_passing_stack_from_factory,
    build_stack_from_factory,
    run_functional_message_passing_stack,
    run_stack,
    run_functional_message_passing_stack_complete,
    run_stack_complete,
)


# =============================================================================
# Public export inventory
# =============================================================================

__all__ = (
    "FUNCTIONAL_MESSAGE_PASSING_STACK_SCHEMA_VERSION",
    "STACK_INPUTS_SCHEMA_VERSION",
    "STACK_DEPTH_RECORD_SCHEMA_VERSION",
    "STACK_TRACE_SCHEMA_VERSION",
    "STACK_COMPUTATION_OUTPUT_SCHEMA_VERSION",
    "STACK_PUBLIC_OUTPUT_SCHEMA_VERSION",
    "STACK_RUN_SCHEMA_VERSION",
    "STACK_RUN_WITH_DIAGNOSTICS_SCHEMA_VERSION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_OPERATION_ORDER",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_SCIENTIFIC_INTERPRETATION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_OUTPUT_SCHEMA",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_REIMPLEMENTS_LAYER_MATH",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_RETENTION_AFFECTS_NUMERICS",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_TRACE_AFFECTS_NUMERICS",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_DIAGNOSTICS_AFFECT_NUMERICS",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_HIDDEN_WIDTH_CHANGES_SUPPORTED",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_ZERO_LAYER_SUPPORTED",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_PARTIAL_SHARING_SUPPORTED",
    "expected_retained_layer_indices",
    "FunctionalMessagePassingStackInputs",
    "StackInputs",
    "FunctionalMessagePassingStackDepthRecord",
    "StackDepthRecord",
    "FunctionalMessagePassingStackTrace",
    "StackTrace",
    "FunctionalMessagePassingStackComputationOutput",
    "StackComputationOutput",
    "FunctionalMessagePassingStackOutput",
    "StackOutput",
    "FunctionalMessagePassingStackRun",
    "StackRun",
    "FunctionalMessagePassingStackRunWithDiagnostics",
    "StackRunWithDiagnostics",
    "assemble_functional_message_passing_stack_output",
    "assemble_stack_output",
    "validate_public_stack_output",
    "validate_functional_message_passing_stack_run",
    "validate_stack_run",
    "STACK_SHARING_POLICY_SCHEMA_VERSION",
    "STACK_LAYER_SHARING_PLAN_SCHEMA_VERSION",
    "STACK_SHARING_POLICY_AFFECTS_NUMERICAL_ARCHITECTURE",
    "STACK_SHARING_POLICY_AFFECTS_PARAMETER_OWNERSHIP",
    "STACK_SHARING_POLICY_AFFECTS_TRACE_DETAIL",
    "STACK_SHARING_POLICY_AFFECTS_OUTPUT_RETENTION",
    "STACK_SHARING_POLICY_AFFECTS_DIAGNOSTICS",
    "STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_MODULES",
    "STACK_SHARING_INDEPENDENT_REQUIRES_DISTINCT_PARAMETERS",
    "STACK_SHARING_FULLY_SHARED_REQUIRES_EXACT_MODULE_REUSE",
    "STACK_SHARING_PARTIAL_SUPPORTED",
    "STACK_SHARING_SCIENTIFIC_INTERPRETATION",
    "INDEPENDENT_LAYER_STATE_DICT_PREFIX",
    "FULLY_SHARED_LAYER_STATE_DICT_PREFIX",
    "normalize_stack_sharing_policy",
    "normalize_sharing_policy",
    "assert_stack_sharing_policy_implemented",
    "is_independent_stack_sharing_policy",
    "is_fully_shared_stack_sharing_policy",
    "StackSharingPolicy",
    "SharingPolicy",
    "resolve_stack_sharing_policy",
    "resolve_sharing_policy",
    "StackLayerSharingPlan",
    "LayerSharingPlan",
    "build_independent_stack_layer_sharing_plan",
    "build_fully_shared_stack_layer_sharing_plan",
    "build_stack_layer_sharing_plan",
    "build_layer_sharing_plan",
    "build_stack_layer_sharing_plan_from_factory",
    "build_layer_sharing_plan_from_factory",
    "validate_stack_layer_sharing_plan",
    "validate_layer_sharing_plan",
    "layer_for_stack_depth",
    "STACK_RETENTION_POLICY_SCHEMA_VERSION",
    "STACK_TRACE_POLICY_SCHEMA_VERSION",
    "STACK_TRACE_DECISION_SCHEMA_VERSION",
    "STACK_RETENTION_AFFECTS_NUMERICAL_RESULTS",
    "STACK_LAYER_TRACE_AFFECTS_NUMERICAL_RESULTS",
    "STACK_AUDIT_MODE_AFFECTS_NUMERICAL_RESULTS",
    "STACK_RETENTION_NONE_RETAINS_FINAL_LAYER",
    "STACK_RETENTION_FINAL_LAYER_RETAINS_FINAL_LAYER",
    "STACK_RETENTION_ALL_LAYERS_RETAINS_FINAL_LAYER",
    "STACK_RETENTION_POLICY_IS_OUTPUT_CONTRACT",
    "STACK_LAYER_TRACE_POLICY_IS_OUTPUT_CONTRACT",
    "STACK_TRACE_POLICY_IS_NUMERICAL_ARCHITECTURE",
    "STACK_TRACE_POLICY_SCIENTIFIC_INTERPRETATION",
    "normalize_stack_retention_policy",
    "normalize_retention_policy",
    "assert_stack_retention_policy_implemented",
    "resolve_stack_retention_policy",
    "resolve_retention_policy",
    "is_no_stack_retention",
    "is_final_layer_stack_retention",
    "is_all_layers_stack_retention",
    "StackRetentionPolicy",
    "RetentionPolicy",
    "StackTraceDecision",
    "TraceDecision",
    "StackTracePolicy",
    "TracePolicy",
    "resolve_stack_trace_policy",
    "resolve_trace_policy",
    "build_stack_trace_policy",
    "build_trace_policy",
    "build_stack_trace_decisions",
    "build_trace_decisions",
    "validate_stack_trace_decisions",
    "validate_trace_decisions",
    "validate_retained_layer_indices",
    "assert_stack_trace_policy_matches",
    "stack_trace_policies_are_numerically_equivalent",
    "STACK_DIAGNOSTIC_THRESHOLDS_SCHEMA_VERSION",
    "STACK_DEPTH_DIAGNOSTIC_SCHEMA_VERSION",
    "STACK_DIAGNOSTIC_REPORT_SCHEMA_VERSION",
    "STACK_DIAGNOSTICS_SCHEMA_VERSION",
    "STACK_DIAGNOSTICS_AFFECT_NUMERICAL_RESULTS",
    "STACK_DIAGNOSTICS_RETAIN_AUTOGRAD_REFERENCES",
    "STACK_DIAGNOSTICS_RETURN_TENSORS",
    "STACK_DIAGNOSTICS_ESTABLISH_CAUSALITY",
    "STACK_DIAGNOSTICS_ESTABLISH_FAITHFULNESS",
    "STACK_DIAGNOSTICS_ESTABLISH_CALIBRATION",
    "STACK_DIAGNOSTICS_ESTABLISH_IDENTIFIABILITY",
    "STACK_DIAGNOSTIC_DEPTH_SOURCE_AUDIT_TRACE",
    "STACK_DIAGNOSTIC_DEPTH_SOURCE_RETAINED_OUTPUT",
    "STACK_DIAGNOSTIC_DEPTH_SOURCE_UNAVAILABLE",
    "CANONICAL_STACK_DIAGNOSTIC_DEPTH_SOURCES",
    "STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_COLLAPSE",
    "STACK_DIAGNOSTIC_ALERT_TOTAL_STATE_EXPLOSION",
    "STACK_DIAGNOSTIC_ALERT_TOTAL_UPDATE_LARGE",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_COLLAPSE",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_STATE_EXPLOSION",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_LARGE",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_UPDATE_TINY",
    "STACK_DIAGNOSTIC_ALERT_DEPTH_DIRECTION_REVERSAL",
    "STACK_DIAGNOSTIC_ALERT_INCOMPLETE_DEPTH_COVERAGE",
    "STACK_DIAGNOSTIC_ALERT_SHARED_PARAMETER_DRIFT",
    "STACK_DIAGNOSTIC_ALERT_SHARED_ARCHITECTURE_DRIFT",
    "STACK_DIAGNOSTIC_SCIENTIFIC_CLAIMS",
    "StackDiagnosticThresholds",
    "DiagnosticThresholds",
    "StackDepthDiagnostic",
    "DepthDiagnostic",
    "FunctionalMessagePassingStackDiagnosticReport",
    "StackDiagnosticReport",
    "build_functional_message_passing_stack_diagnostic_report",
    "build_stack_diagnostic_report",
    "build_diagnostic_report",
    "validate_functional_message_passing_stack_diagnostic_report",
    "validate_stack_diagnostic_report",
    "validate_diagnostic_report",
    "FunctionalMessagePassingStackDiagnostics",
    "StackDiagnostics",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_MODULE_SCHEMA_VERSION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STACKING_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_LAYER_MATH_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_PREDICTION_OWNED_HERE",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CLONES_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_DETACHES_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_CASTS_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_STATE_REBINDING_MOVES_TENSOR",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_REGULARIZATION_REDUCTION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_AUDIT_RETENTION",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_INDEPENDENT_REGISTRATION_PREFIX",
    "FUNCTIONAL_MESSAGE_PASSING_STACK_FULLY_SHARED_REGISTRATION_PREFIX",
    "derive_next_functional_message_passing_inputs",
    "derive_next_layer_inputs",
    "validate_rebound_functional_message_passing_inputs",
    "validate_rebound_inputs",
    "FunctionalMessagePassingStack",
    "HazardConditionedFunctionalMessagePassingStack",
    "FunctionalStack",
    "MessagePassingStack",
    "build_functional_message_passing_stack",
    "build_stack",
    "build_functional_message_passing_stack_from_factory",
    "build_stack_from_factory",
    "run_functional_message_passing_stack",
    "run_stack",
    "run_functional_message_passing_stack_complete",
    "run_stack_complete",
)
